
cluster.name: "testing"
node.name: "node-01"

http.host: 0.0.0.0
http.cors.enabled: true
http.cors.allow-origin: "*"

cluster.initial_master_nodes:
  - "node-01"
discovery.zen.ping.unicast.hosts:
  - localhost 

# path:
#   logs: /data/elk/log
#   data: /data/elk/data

indices.query.bool.max_clause_count: 2000

xpack.license.self_generated.type: basic
xpack.security.enabled: false
xpack.ml.enabled: false
