server.name: kibana
server.host: "0.0.0.0"
kibana.defaultAppId: "dashboards"
server.rewriteBasePath: false

elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.requestTimeout: 60000
elasticsearch.shardTimeout: 60000

xpack.infra.enabled: false 
# xpack.logstash.enabled: false
xpack.canvas.enabled: false
xpack.spaces.enabled: false
xpack.apm.enabled: false
xpack.security.enabled: false
xpack.uptime.enabled: false
xpack.siem.enabled: false
xpack.ml.enabled: false
xpack.monitoring.enabled: false
xpack.graph.enabled: false
xpack.grokdebugger.enabled: false


telemetry.enabled: false
telemetry.optIn: false